My_First_Project/My_First_Project/urls.py
from django.contrib import admin
from django.urls import path

#for link-up with app urls file
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_app.urls')),

]

My_First_Project/first_app/urls.py
from django.conf.urls import url
from django.urls import path

from first_app import views


#app name added for relative urls
app_name = "first_app"


urlpatterns = [
    path('', views.index, name='home'),#this name='home' use for relative urls
    path('add_album/', views.albumForm, name='album_Form'),
    path('add_musician/', views.musicianForm, name='musician_Form'),
    path('album_list/<int:artist_id>/', views.albumList, name='album_list'),
    path('edit_artist/<int:id>/', views.editArtist, name='edit_artist'),
    path('edit_album/<int:album_id>/', views.editAlbum, name='edit_album'),
    path('delete_album/<int:album_id>/', views.deleteAlbum, name='delete_album'),
    path('delete_artist/<int:artist_id>/', views.deleteArtist, name='delete_artist')
]

My_First_Project/first_app/models.py
from django.db import models

# Create your models here.
class Musician(models.Model):
    #id = models.AutoField(Primary_key = True)
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    instrument = models.CharField(max_length = 100)

    def __str__(self):
        return self.first_name + " "+ self.last_name + " "+ self.instrument




class Album(models.Model):
    #id = models.AutoField(Primary_key = True)
    artist = models.ForeignKey(Musician, on_delete=models.CASCADE)
    name = models.CharField(max_length = 100)
    release_date = models.DateField()
    rating = (
        (1, "Worst"),
        (2, "Bad"),
        (3, "Not Bad"),
        (4, "Good"),
        (5, "Excellent!"),
    )
    num_stars = models.IntegerField(choices=rating)

    def __str__(self):
        return self.name + ", Rating : "+ str(self.num_stars)

My_First_Project/first_app/forms.py
from django import forms
from datetime import date

#validation library import
from django.core import validators


#import Models induvitual
#from first_app.models import Album, Musician

#import all model
from first_app import models

#get today date
today = date.today()


class MusicianForm(forms.ModelForm):

    first_name = forms.CharField(widget=forms.TextInput(attrs=
        {'placeholder': 'First Name', 'style':'width:300px; height:33px; border: 1px solid gray; border-radius:2px;'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs=
        {'placeholder': 'Last Name', 'style':'width:300px; height:33px; border: 1px solid gray; border-radius:2px;'}))
    instrument = forms.CharField(widget=forms.TextInput(attrs=
        {'placeholder': 'Instrument', 'style':'width:300px; height:33px; border: 1px solid gray; border-radius:2px;'}))

    class Meta:
        model = models.Musician
        fields = "__all__"

class AlbumForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs=
        {'placeholder': 'Album Name', 'style':'width:300px; height:33px; border: 1px solid gray; border-radius:2px;'}))

    release_date = forms.DateField(widget= forms.DateInput(attrs=
        {'type':'date' ,'style':'width:300px; height:33px; border: 1px solid gray; border-radius:2px;'}))
    class Meta:
        model = models.Album
        fields = "__all__"

My_First_Project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

#Models import
from first_app.models import Musician, Album
#import forms
from first_app import forms
#datbase function Added
from django.db.models import Avg


def index(request):
    Musician_list = Musician.objects.order_by('id')
    diction = {
        'title': "Home Page",
        'Musician_list':Musician_list
    }
    return render(request, 'first_app/index.html', context=diction)

def albumList(request, artist_id):
    artist_info = Musician.objects.get(pk=artist_id)
    album_list = Album.objects.filter(artist=artist_info.id).order_by('release_date', 'name')
    artist_rating = Album.objects.filter(artist=artist_info.id).aggregate(Avg('num_stars'))
    diction = {
        'title': "Album Page",
        'artist_info':artist_info,
        'album_list':album_list,
        'artist_rating':artist_rating
    }
    return render(request, 'first_app/album_list.html', context=diction)


def musicianForm(request):
    new_form = forms.MusicianForm()
    if request.method == "POST":
         new_form = forms.MusicianForm(request.POST)
         if new_form.is_valid():
             new_form.save(commit=True)
             return index(request)

    diction = {
        'title': "Add Musician",
        'Musician_Form' : new_form
    }
    return render(request, 'first_app/musician_form.html', context=diction)



def albumForm(request):
    album_form = forms.AlbumForm()

    if request.method == "POST":
        album_form = forms.AlbumForm(request.POST)
        if album_form.is_valid():
            album_form.save(commit=True)
            return index(request)
    diction = {
        'title': "Add Album",
        'album_form': album_form
    }
    return render(request, 'first_app/album_form.html', context=diction)

def editArtist(request, id):
    artist_info = Musician.objects.get(pk=id)
    new_form = forms.MusicianForm(instance=artist_info)

    if request.method == "POST":
        new_form = forms.MusicianForm(request.POST, instance=artist_info)
        if new_form.is_valid():
            new_form.save(commit=True)
            return albumList(request, artist_info.id)

    diction = {
        'title': "Edit Musician",
        'Musician_Form' : new_form
    }
    return render(request, 'first_app/edit_artist.html', context=diction)

def editAlbum(request, album_id):
    album_info = Album.objects.get(pk=album_id)
    album_form = forms.AlbumForm(instance=album_info)
    diction={'title': "Edit Album",}
    if request.method == "POST":
        album_form = forms.AlbumForm(request.POST, instance=album_info)
        if album_form.is_valid():
            album_form.save(commit=True)
            diction.update({
                'success_text':'Successfully Updated'
            })
            # return albumList(request, album_info.artist_id)

    diction.update({
        'album_form':album_form,
        'album_id':album_id
    })
    return render(request, 'first_app/edit_album.html', context=diction)

def deleteAlbum(request, album_id):
    album = Album.objects.get(pk=album_id).delete()
    diction = {
        'title':'Delete View',
        'success_text':'Successfully Deleted this Album!'
    }
    return render(request, 'first_app/delete_album.html', context=diction)


def deleteArtist(request, artist_id):
    aritist = Musician.objects.get(pk=artist_id).delete()
    diction = {
        'title':'Delete View',
        'success_text':'Successfully Deleted this Aritist!'
    }
    return render(request, 'first_app/delete_album.html', context=diction)

My_First_Project/templates/first_app/album_form.html
{% extends "first_app/base.html" %}
{% block body_block %}

<h1 align="center">Album page</h1>
<div class="row" align="center">
  <div class="col-md-12" style="margin-top:20px;">
    <form class="form-horizontal" align="center" method="post">
      {{ album_form.as_p }}
      {% csrf_token %}
      <input class="btn btn-success" type="submit" name="submit" value="SUBMIT">
    </form>
  </div>
</div>

{% endblock %}

My_First_Project/templates/first_app/album_list.html
{% extends "first_app/base.html" %}
{% block body_block %}

<h2 align="center">Artist Name : {{ artist_info.first_name }} {{ artist_info.last_name }} </h2>
<h2 align="center" > Instrument : {{ artist_info.instrument }} </h2>

<a style="margin-bottom:10px;" class="btn btn-primary btn-md"
href="{% url 'first_app:edit_artist' id=artist_info.id %}">Edit</a>

<a style="margin-bottom:10px;" onclick="return confirm('Are Your Sure!')" class="btn btn-danger btn-md"
href="{% url 'first_app:delete_artist' artist_id=artist_info.id %}">Delete</a>


<h1 align="center" style="background-color:lightblue;">Artist Album list page</h1>
<div class="row" align="center">
  <div class="col-md-12 table-responsive" style="margin-top:20px;">
    <table class="table">
      <tr>
        <th><b>Album Name</b></th>
        <th><b>Relase Date</b></th>
        <th><b>Reating</b></th>
        <th><b>Action</b></th>
      </tr>
    {% if album_list %}
      {% for row in album_list %}
          <tr>
            <td>{{ row.name }}</td>
            <td>{{ row.release_date }}</td>
            <td>{{ row.num_stars }}</td>
            <td><a class="btn btn-info btn-md" href="{% url 'first_app:edit_album' album_id=row.id %}">Edit</a></td>
          </tr>
      {% endfor %}
          <tr>
            <td colspan="2" align="center"><b>All rating</b></td>
            <td colspan="2"><b>{{ artist_rating.num_stars__avg }}</b></td>
          </tr>
    {% else %}
      <tr>
        <td colspan="3">No Album</td>

      </tr>
    {% endif %}
    </table>
  </div>
</div>

{% endblock %}

My_First_Project/templates/first_app/base.html
<!DOCTYPE html>
<html lang="" dir="ltr">
  <head>
    <!-- Latest compiled and minified CSS -->
<!-- Optional theme -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <meta charset="utf-8">
    <title>{{ title }}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'first_app:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'first_app:musician_Form' %}">Add Musician</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'first_app:album_Form' %}">Add Album</a>
        </li>

      </ul>
    </nav>

    <div class="container" align="center">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

My_First_Project/templates/first_app/delete_album.html
{% extends "first_app/base.html" %}
{% block body_block %}


{% if success_text %}
<div class="alert alert-danger" style="margin-top:10px;" role="alert">
  {{ success_text }}
</div>
{% endif %}


{% endblock %}

My_First_Project/templates/first_app/edit_album.html
{% extends "first_app/base.html" %}
{% block body_block %}


<h1 align="center">Edit Album</h1>
{% if success_text %}
<div class="alert alert-success" role="alert">
  {{ success_text }}
</div>
{% endif %}
<div class="row" align="center">
  <div class="col-md-12" style="margin-top:20px;">
    <form class="form-horizontal" align="center" method="post">
      {{ album_form.as_p }}
      {% csrf_token %}
      <input class="btn btn-success" type="submit" name="submit" value="Edit">
      <a onclick="return confirm('Are you sure to delete this Album!')" class="btn btn-danger"
      href="{% url 'first_app:delete_album' album_id=album_id %}">Delete</a>
    </form>
  </div>
</div>



{% endblock %}

My_First_Project/templates/first_app/edit_artist.html
{% extends "first_app/base.html" %}
{% block body_block %}


<h1 align="center">Edit Artist</h1>
<div class="row" align="center">
  <div class="col-md-12" style="margin-top:20px;">
    <form class="form-horizontal" align="center" method="post">
      {{ Musician_Form.as_p }}
      {% csrf_token %}
      <input class="btn btn-primary" type="submit" name="submit" value="Edit">
    </form>
  </div>
</div>


{% endblock %}

My_First_Project/templates/first_app/index.html
{% extends "first_app/base.html" %}
{% block body_block %}

<h1 align="center">Musician list page</h1>
<div class="row" align="center">
  <div class="col-md-12 table-responsive" style="margin-top:20px;">
    <table class="table">
      <tr>
        <th><b>First Name</b></th>
        <th><b>Last Name</b></th>
        <th><b>Instrument</b></th>
      </tr>
    {% if Musician_list%}
      {% for row in Musician_list %}
          <tr>
            <td><a href="{% url 'first_app:album_list' artist_id=row.id %}">{{ row.first_name }}</a></td>
            <td>{{ row.last_name }}</td>
            <td>{{ row.instrument }}</td>
          </tr>
      {% endfor %}
    {% else %} 
      <tr>
        <td colspan="3">No Musicians</td>

      </tr>
    {% endif %}
    </table>
  </div>
</div>

{% endblock %}

My_First_Project/templates/first_app/musician_form.html
{% extends "first_app/base.html" %}
{% block body_block %}

<h1 align="center">Musician page</h1>
<div class="row" align="center">
  <div class="col-md-12" style="margin-top:20px;">
    <form class="form-horizontal" align="center" method="post">
      {{ Musician_Form.as_p }}
      {% csrf_token %}
      <input class="btn btn-success" type="submit" name="submit" value="SUBMIT">
    </form>
  </div>
</div>


{% endblock %}